#!/bin/bash

# Update Git submodules
git submodule update --init

# Install Python packages using pip
pip install flask_cors bs4 lxml pelican markdown gevent
 install
# Optionally, you can add more commands or customizationspip install flask_cors bs4 lxml pelican markdown gevent here.